#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'git'
cookbook 'sqlite'
cookbook 'mysql'
cookbook 'memcached'
cookbook 'postgresql'
cookbook 'nodejs'
cookbook 'database'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'
